config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    member do
      post :vote_movie
      post :unvote_movie
    end
  end
  resources :votes do
  end
  devise_for :users
  root "movies#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reactions

  def youtube_id
    if self.link.present?
      if self.link.include?('/') && self.link.include?('youtu')
        link = self.link.split('/')
        if link.present?
          link.last
        else
          nil
        end
      else
        nil
      end
    else
      nil
    end
  end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  enum reaction_type: [:vote, :unvote]

  scope :who_voted, ->(user_id) {where(user_id: user_id)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :movies
  has_many :reactions

  attr_writer :login

  def login
    @login || self.username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :password, :password_confirmation, :remember_me])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :vote_movie, :unvote_movie]

  def index
    @movies = Movie.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @user = current_user
    if @user.present?
      @movie = @user.movies.create(movie_params)
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie.update(movie_params)
    redirect_to movies_path
  end

  def destroy
  end

  def vote_movie
    @user = current_user
    if @movie.present? && @user.present?
      @vote = @user.reactions.create(movie_id: @movie.id, reaction_type: params[:type])
      number = @movie.votes.to_i + 1
      update_votes = @movie.update_attribute(:votes, number)
      if @vote && update_votes
        flash[:notice] = "Reaction success"
      else
        flash[:notice] = "Reaction error"
      end
    end
    redirect_to movies_path
  end

  def unvote_movie
    @user = current_user
    if @movie.present? && @user.present?
      @vote = @user.reactions.create(movie_id: @movie.id, reaction_type: params[:type])
      number = @movie.unvotes.to_i + 1
      update_votes = @movie.update_attribute(:unvotes, number)
      if @vote && update_votes
        flash[:notice] = "Reaction success"
      else
        flash[:notice] = "Reaction error"
      end
    end
    redirect_to movies_path
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end

  protected

  def movie_params
    params.require(:movie).permit(:link, :title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funnymovie</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/nav" %>
    <%= render "partials/flash" %>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for movie do |f| %>
  <div class="container">
    <div class="row">
      <div class="mb-3">
        <%= f.label :title %>
        <%= f.input_field :title, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :description %>
        <%= f.input_field :description, as: :text, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :link %>
        <%= f.input_field :link, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.button :submit, class: "btn btn-success" %>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/movies/edit.html.erb
<div class="padding">
  <%= render partial: "form", locals: {movie: @movie} %>
</div>

app/views/movies/index.html.erb
<% if user_signed_in? %>
  <div class="container mb-3">
    <div class="dropdown text-end">
      <%= link_to 'Share Movie', new_movie_path, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
<div class="album py-3 bg-light">
  <div class="container">
    <% if @movies.present? %>
      <% @movies.each do |m| %>
        <div class="row my-5">
          <div class="col-12 col-sm-6 col-md-6">
            <div class="card shadow-sm">
              <% if m.youtube_id.present? %>
                <iframe width="auto" height="315" src="https://www.youtube.com/embed/<%= m.youtube_id %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              <% else %>
                <svg class="bd-placeholder-img card-img-top" width="100%" height="300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="45%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
              <% end %>
            </div>
          </div>
          <div class="col-12 col-sm-6 col-md-6">
            <div class="card shadow-sm">
              <div class="card-body">
                <p class="card-text text-start text-capitalize text-danger"><%= m.title %></p>
                <p class="card-text text-start">
                  <%= "Shared by #{m.user&.username}" %>
                  <% reactioned = m.reactions.who_voted(current_user&.id) %>
                  <% if reactioned.present? %>
                    <% if reactioned.first.vote? %>
                      <span class="ms-2"><i class="fas fa-thumbs-up fa-3x"></i></span>
                    <% else %>
                      <span class="ms-2"><i class="fas fa-thumbs-down fa-3x"></i></span>
                    <% end %>
                  <% else %>
                    <span>
                    <%= link_to vote_movie_movie_path(id: m.id, type: :vote),
                                method: :post,
                                data: {
                                  confirm: 'Are you sure?'
                                },
                                class: "btn #{'d-none' unless user_signed_in? }",
                                remote: true do %>
                      <i class="far fa-thumbs-up ps-1 fa-2x"></i>
                    <% end %>
                  </span>
                    <span class="ps-3">
                    <%= link_to unvote_movie_movie_path(id: m.id, type: :unvote),
                                method: :post,
                                data: {
                                  confirm: 'Are you sure?'
                                },
                                class: "btn #{'d-none' unless user_signed_in? }",
                                remote: true do %>
                      <i class="far fa-thumbs-down ps-1 fa-2x"></i>
                    <% end %>
                  </span>
                  <% end %>
                </p>
                <p>
                  <span><%= m.votes.to_i %><i class="far fa-thumbs-up ps-1"></i></span>
                  <span class="ps-3"><%=  m.unvotes.to_i %><i class="far fa-thumbs-down ps-1"></i></span>
                </p>
                <p class="card-text text-start text-capitalize">description:</p>
                <p class="card-text text-start text-break"><strong><%= m.description %></strong></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
<div class="padding">
  <%= render partial: "form", locals: {movie: @movie} %>
</div>

app/views/movies/show.html.erb
<h1>Movies#show</h1>
<p>Find me in app/views/movies/show.html.erb</p>

app/views/movies/update.html.erb
<h1>Movies#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/partials/_flash.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/partials/_nav.html.erb
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li class="nav-item"><%= link_to "Funnymovie", root_path, class: "nav-link" %></li>
      </ul>

<!--      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">-->
<!--        <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">-->
<!--      </form>-->
      <% if user_signed_in? %>
        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="text-success me-2"><%= "Welcome, #{current_user.username}" %></span><img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><%= link_to "Sign out", destroy_user_session_path, class: 'text-danger dropdown-item', method: :delete %></li>
          </ul>
        </div>
      <% else %>
        <div class="text-end">
          <%= link_to "Login", new_user_session_path, type: "button", class: "btn btn-outline-primary me-2" %>
          <%= link_to "Register", new_user_registration_path, type: "button", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/reactions/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/reactions/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

app/views/reactions/edit.html.erb
<h1>Votes#edit</h1>
<p>Find me in app/views/votes/edit.html.erb</p>

app/views/reactions/index.html.erb
<h1>Votes#index</h1>
<p>Find me in app/views/votes/index.html.erb</p>

app/views/reactions/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>

app/views/reactions/show.html.erb
<h1>Votes#show</h1>
<p>Find me in app/views/votes/show.html.erb</p>

app/views/reactions/update.html.erb
<h1>Votes#update</h1>
<p>Find me in app/views/votes/update.html.erb</p>